config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do   
      resources :todo_lists do
        resources :todo_items do
          member do
            post :complete
            post :incomplete
            post :move
            patch :edit
          end
        end
      end
    end
  end



  get 'search/index'
  post 'search/index'

  
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
   validates :name, presence: true
   belongs_to :todo_list
   has_many :tags, :dependent => :destroy
     
   
end

app/controllers/api/v1/todo_items_controller.rb
require 'date'

module Api::V1

class TodoItemsController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_item, except: [:index, :create]
    skip_before_action :verify_authenticity_token

   
    def show
    end

    def index
        
        @dropdown_items = TodoList.all.where("id <> " + @todo_list.id.to_s)        
        @todoitems = @todo_list.todo_items.all.includes(:tags)

         returnlist = []

        @todoitems.each do |item|
           list = {
               id: item.id,
               name: item.name,
               completed: item.completed == true ? 'Yes' : 'No' ,
               datecompleted: item.datecompleted,
               isrecurring: item.isrecurring == true ? 'Yes' : 'No',
               tags: item.tags
           }
           returnlist << list
        end       


        render json:returnlist

    end

    def edit
        
        if request.patch?
   
            if @todoitem.update(todo_items_params_edit[:todo_item])

                TodoItemManager.SaveTags(@todoitem, todo_items_params_edit)    
                flash[:topnotice] = 'Todo item updated successully.'
                redirect_to todo_list_todo_items_path(@todo_list)
                
            else

                render 'edit'

            end    

        end     
        
    end
  
    def create

        unless todo_items_params[:name].empty?
            
            @todo_item = @todo_list.todo_items.create(todo_items_params)
           
            if @todo_item.id > 0

                TodoItemManager.SaveTags(@todo_item, params.permit(:tagname))
                
                render json: {message: 'Successfully created'}, status: :ok

            else

                render json: {message: 'Could not be saved'}, status: :unprocessable_entity
                #flash[:errors] = "Unknown error occured"

            end

            #redirect_to todo_list_todo_items_path(@todo_list)
            
        else
            
            render json: {message: 'Could not be saved'}, status: :unprocessable_entity

            #flash[:errors] = "Name can't be blank"
            #redirect_to todo_list_todo_items_path(@todo_list)

        end

    end

    def destroy
        
        @todoitem.destroy
        render json: {message: 'Successfully deleted'}, status: :ok
        #flash[:topnotice] = 'Item deleted successully.'
        #redirect_to todo_list_todo_items_path(@todo_list)

    end

    def move
        
        @todoitem.update(todo_list_id: params[:newtodo])
        render json: {message: 'Successfully moved'}, status: :ok
        #flash[:topnotice] = 'Item moved successully.'
        #redirect_to todo_list_todo_items_path(@todo_list)

    end

    def complete
        
        @todoitem.update(completed: true, datecompleted: DateTime.now)
        render json: {message: 'Status changed'}, status: :ok
        #flash[:topnotice] = 'Marked as completed successully.'
        #redirect_to todo_list_todo_items_path(@todo_list)

    end

    def incomplete
        
        @todoitem.update(completed: false, datecompleted: nil)
        render json: {message: 'Status changed'}, status: :ok
        #flash[:topnotice] = 'Marked as incomplete successully.'
        #redirect_to todo_list_todo_items_path(@todo_list)

    end
    
    private

    def set_todo_list
        
        @todo_list = TodoList.find(params[:todo_list_id])

    end

    def set_todo_item
        
        @todoitem = @todo_list.todo_items.find(params[:id])

    end

    def todo_items_params
        
        params.permit(:name,:isrecurring)

    end

    def todo_items_params_edit
        
        params.permit(:tagname, todo_item: {})

    end    


end

end

app/controllers/todo_items_controller.rb
require 'date'

class TodoItemsController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_item, except: [:index, :create]
   
    def show
    end

    def index
        
        @dropdown_items = TodoList.all.where("id <> " + @todo_list.id.to_s)        
        @todoitems = @todo_list.todo_items.all.includes(:tags)

    end

    def edit
        
        if request.patch?
   
            if @todoitem.update(todo_items_params_edit[:todo_item])

                TodoItemManager.SaveTags(@todoitem, todo_items_params_edit)    
                flash[:topnotice] = 'Todo item updated successully.'
                redirect_to todo_list_todo_items_path(@todo_list)
                
            else

                render 'edit'

            end    

        end     
        
    end
  
    def create

        unless todo_items_params[:name].empty?
            
            @todo_item = @todo_list.todo_items.create(todo_items_params)
           
            if @todo_item.id > 0

                TodoItemManager.SaveTags(@todo_item, params.permit(:tagname))
                
            else

                flash[:errors] = "Unknown error occured"

            end

            redirect_to todo_list_todo_items_path(@todo_list)
            
        else
            
            flash[:errors] = "Name can't be blank"
            redirect_to todo_list_todo_items_path(@todo_list)

        end

    end

    def destroy
        
        @todoitem.destroy
        flash[:topnotice] = 'Item deleted successully.'
        redirect_to todo_list_todo_items_path(@todo_list)

    end

    def move
        
        @todoitem.update(todo_list_id: params[:newtodo])
        flash[:topnotice] = 'Item moved successully.'
        redirect_to todo_list_todo_items_path(@todo_list)

    end

    def complete
        
        @todoitem.update(completed: true, datecompleted: DateTime.now)
        flash[:topnotice] = 'Marked as completed successully.'
        redirect_to todo_list_todo_items_path(@todo_list)

    end

    def incomplete
        
        @todoitem.update(completed: false, datecompleted: nil)
        flash[:topnotice] = 'Marked as incomplete successully.'
        redirect_to todo_list_todo_items_path(@todo_list)

    end
    
    private

    def set_todo_list
        
        @todo_list = TodoList.find(params[:todo_list_id])

    end

    def set_todo_item
        
        @todoitem = @todo_list.todo_items.find(params[:id])

    end

    def todo_items_params
        
        params.permit(:name,:isrecurring)

    end

    def todo_items_params_edit
        
        params.permit(:tagname, todo_item: {})

    end    


end

app/helpers/todo_items_helper.rb
module TodoItemsHelper

    def TodoItemsHelper.GetTags(todo_item)
      
        tagnames = ''
  
        todo_item.tags.each do |tag|
           tagnames << tag.tagname + ', '
        end
  
        if tagnames.length > 0
           tagnames.delete_suffix(', ')
        else
            ''
        end
  
     end

end

app/views/todo_items/_form.html.erb
 <%= form_with(model: todoitem, local:true) do |form|%>    

    <div class="table">
        <div class="row"><b>Add New ToDo:</b></div>
        <% unless flash[:errors].nil? %>
            <div id="error_explanation">
            <ul>        
                <li><%= flash[:errors] %></li>
            </ul>
            </div>
        <%end%>        
        <div class="row">
            <div><%=form.label :Name %></div>
            <div><%=form.text_field :name, size: 40 %></div>
            <div><%=form.label :Tags %></div>            
            <input type="input" value="To Do" name="tagname" id="tagname" data-role="tagsinput"><br>            
            <input type="checkbox" name="isrecurring" id="isrecurring"> Recurring
            <br><br>
            <%= link_to 'Back', todo_lists_path %>&nbsp;&nbsp;&nbsp;&nbsp;<%=form.submit :Add, class: 'button'%>
        </div>            
    </div>

<%end%>        


    

app/views/todo_items/_form2.html.erb
 <%= form_with(model: [:edit, @todo_list, todoitem], local:true) do |form|%>
    <div class="table">
        <div class="row"><b>Add ToDo:</b></div>

        <% if todoitem.errors.any? %>
        <div id="error_explanation">
        <h4><%= pluralize(todoitem.errors.count, "error") %> found:</h4>
        <ul>
            <% todoitem.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
        <% end %>

        <div class="row">
            <br>
            <div><%=form.label :Name %></div>
            <div><%=form.text_field :name, size: 40 %></div>
            <br>
            <div><%=form.label :Tags %></div>                       
            <input type="input" value="<%=todoitem.GetTags%>" name="tagname" id="tagname" data-role="tagsinput"><br>
            <br>
            <div><%=form.check_box  :isrecurring%>Recurring</div>
            <br><br>
            <%= link_to 'Back', todo_list_todo_items_path(@todo_list) %>&nbsp;&nbsp;&nbsp;&nbsp;
            <%=form.submit :Update, class: 'button'%>
        </div>            
    </div>

<%end%>        


    

app/views/todo_items/edit.html.erb
<div class="wrapper" style="padding-bottom: 0px;">
    <div class="fontblue"><h1>Edit Todo Item</h1></div>    
    <%= render 'todo_items/form2', todoitem: @todoitem%>
</div>

app/views/todo_items/index.html.erb
<div class="wrapper">
  <div class="fontblue"><h1>Todo Items</h1></div>    
    <p id="notice"><%= flash[:topnotice] %></p>  
    <br>
    <div class="table">    
      
      <div class="row header blue">
        <div class="cell" style="width:30%">Todo Item</div>
        <div class="cell" style="width:5%">Completed</div>      
        <div class="cell" style="width:5%">Recurring</div>      
        <div class="cell" style="width:15%">Date Completed</div>
        <div class="cell" style="width:10%">Tags</div>
        <div class="cell" style="width:10%">Mark Complete</div>
        <div class="cell" style="width:20%">Move</div>
        <div class="cell" style="width:5%">Edit</div>
        <div class="cell" style="width:10%">Delete</div>
      </div>
      <% @todoitems.each do |item|%>

      <div class="row">
          
          <%if item.completed? %>
            <div class="cell completed" style="width:30%"><%=item.name%></div>
          <%else%>
            <div class="cell" style="width:30%"><%=item.name%></div>
          <%end%>

          <div class="cell" style="width:5%"><%= item.completed ? "Yes" : "No" %></div>          
          <div class="cell" style="width:5%"><%= item.isrecurring ? "Yes" : "No" %></div>          
          <div class="cell" style="width:15%"><%=item.datecompleted%></div>
          <div class="cell" style="width:15%"><%= TodoItemsHelper.GetTags(item) %></div>
       
          <%unless item.completed? %>
            <div class="cell" style="width:10%"><%=link_to "Complete", complete_todo_list_todo_item_path(@todo_list,item), method: :complete %></div>
          <%else%>
            <div class="cell" style="width:10%"><%=link_to "Incomplete", incomplete_todo_list_todo_item_path(@todo_list,item), method: :complete %></div>
          <%end%>
          
          <div class="cell" style="width:20%">
          
            <%= form_tag move_todo_list_todo_item_path(@todo_list, item), method: :post do %>

              <%=select_tag "newtodo",options_from_collection_for_select(@dropdown_items,"id","title",@todo_list.id),{onchange: "this.form.submit();", include_blank: "Select"}%>
            
            <%end%>
            
          </div>
          <div class="cell" style="width:10%"><%=link_to "Edit", edit_todo_list_todo_item_path(@todo_list, item)%></div>
          <div class="cell" style="width:10%"><%=link_to "Delete", todo_list_todo_item_path(@todo_list, item), method: :delete, data: {confirm: "are you sure?"}%></div>
      </div>

      <%end%>   
          
    </div>
    
    <%= render 'todo_items/form', todoitem: @todoitem%>
    <%= button_to "Search To Dos Items", search_index_path, class: 'button', method: :get %>
    
</div>  

</div>

app/views/todo_items/search.html.erb
Test

app/views/todo_items/show.html.erb
test