config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do   
      resources :todo_lists do
        resources :todo_items do
          member do
            post :complete
            post :incomplete
            post :move
            patch :edit
          end
        end
      end
    end
  end



  get 'search/index'
  post 'search/index'

  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    validates :title, presence: true
    validates :description, presence:true  
    has_many :todo_items, :dependent => :destroy
    has_many :tags, through: :todo_items

end

app/controllers/api/v1/todo_lists_controller.rb
module Api::V1

class TodoListsController < ApplicationController    
    before_action :set_todo_list, only: %i[ show edit update destroy ]
    skip_before_action :verify_authenticity_token
        
    def index
        
        @todolists = TodoList.all.includes(:todo_items).order(id: :asc)

        returnlist = []

        @todolists.each do |item|
           list = {
               id: item.id,
               title: item.title,
               description: item.description,
               todo_items: item.todo_items
           }
           returnlist << list
        end       

        render json: returnlist

    end

    def new 
        
        @todolist = TodoList.new

    end

    def edit
    end

    def show
    end

    def create
        
        @todolist = TodoList.new(todolist_params)

        if @todolist.save
            
            #flash[:topnotice] = 'New todo list has been created successfully.'                
            #format.html { redirect_to todo_lists_path }
            render json: {message: 'Successfully created'}, status: :ok

        else
            
            render json: @todolist.errors, status: :unprocessable_entity
            #format.html { render :new}

        end      

    end

    def update

        #respond_to do |format|

            if @todolist.update(todolist_params)

                render json: {message: 'Successfully updated'}, status: :ok
                #flash[:topnotice] = 'The todo list has been updated.'
                #format.html { redirect_to todo_lists_path }

            else
                
                #format.html { render :new}
                render json: @todolist.errors, status: :unprocessable_entity


            end
            
        #end

    end
   
    def destroy
        
        if @todolist.destroy            
            
            render json: {message: 'Successfully deleted'}, status: :ok
            #flash[:topnotice] = 'The todo list has been deleted.'

        else
            
            render json: @list.errors, status: :unprocessable_entity
            #flash[:topnotice] = 'Delete failed'

        end

        #redirect_to todo_lists_path

    end

    private

    def todolist_params
        
        params.require(:todo_list).permit(:title,:description)
        
    end

    def set_todo_list
        
        begin
            
            @todolist = TodoList.find(params[:id])

        rescue Exception => e
            
            @todolist = TodoList.new            
            @todolist.errors.add(:base,'Record does not exist')            
            render 'new'

        end      
        
    end

end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
    before_action :set_todo_list, only: %i[ show edit update destroy ]
    
    def index
        
        @todolists = TodoList.all.includes(:todo_items).order(id: :asc)

    end

    def new 
        
        @todolist = TodoList.new

    end

    def edit
    end

    def show
    end

    def create
        
        @todolist = TodoList.new(todolist_params)

        respond_to do |format|

            if @todolist.save
                
                flash[:topnotice] = 'New todo list has been created successfully.'                
                format.html { redirect_to todo_lists_path }

            else
                
                format.html { render :new}

            end

        end

    end

    def update

        respond_to do |format|

            if @todolist.update(todolist_params)

                flash[:topnotice] = 'The todo list has been updated.'
                format.html { redirect_to todo_lists_path }

            else
                
                format.html { render :new}

            end
            
        end

    end
   
    def destroy
        
        if @todolist.destroy            
            
            flash[:topnotice] = 'The todo list has been deleted.'

        else
            
            flash[:topnotice] = 'Delete failed'

        end

        redirect_to todo_lists_path

    end

    private

    def todolist_params
        
        params.require(:todo_list).permit(:title,:description)
        
    end

    def set_todo_list
        
        begin
            
            @todolist = TodoList.find(params[:id])

        rescue Exception => e
            
            @todolist = TodoList.new            
            @todolist.errors.add(:base,'Record does not exist')            
            render 'new'

        end      
        
    end

end

app/helpers/todo_lists_helper.rb
module TodoListsHelper

    
    def TodoListsHelper.GetItems(todo_list)

        items = ''

        todo_list.todo_items.each do |item|
            items << item.name + '<br>'
        end

        if items.length > 0
            items.delete_suffix(', ')
        else
            ""
        end

    end

end

app/views/todo_lists/_form.html.erb
<div class="wrapper">
    <%= form_with(model: todolist, local:true) do |form|%>
    <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(todolist.errors.count, "error") %> found:</h4>
      <ul>
        <% todolist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="table">
        <div class="row">
            <div><%=form.label :Title %></div>
            <div><%=form.text_field :title, size: 98 %></div>
        </div>
        <div class="row">
            <div><%=form.label :Description %></div>
            <div><%=form.text_area :description, cols: 100, rows: 10 %></div>
        </div>       
    </div>
        <%= link_to 'Back', todo_lists_path %>&nbsp;&nbsp;&nbsp;&nbsp;
        <% if todolist.new_record? %>
          <%=form.submit :Add,id: "add", class: 'button'%>
        <%else%>
          <%=form.submit :Update,id: "add", class: 'button'%>
        <%end%>
   <%end%>
</div>

app/views/todo_lists/edit.html.erb
<div class="wrapper" style="padding-bottom: 0px;">
    <%if @todolist.new_record? %>
        <div class="fontblue"><h1>New Todo List</h1></div>
    <%else%>
        <div class="fontblue"><h1>Edit Todo Lists</h1></div>
    <%end%>
</div>

<%= render 'form', todolist: @todolist%>

app/views/todo_lists/index.html.erb
<div class="wrapper">
  <div class="fontblue"><h1>Todo Lists</h1></div>
    <br>    
    <p id="notice"><%= flash[:topnotice] %></p>  
    <br>
    <div class="table">    
    
      <div class="row header blue">
        <div class="cell" style="width:25%">List Name</div>
        <div class="cell" style="width:25%">Description</div>      
        <div class="cell" style="width:25%">Todo Items</div>
        <div class="cell" style="width:8%">Edit</div>
        <div class="cell" style="width:9%">Manage Todo Items</div>
        <div class="cell" style="width:8%">Delete</div>
      </div>
      <% @todolists.each do |list|%>

      <div class="row">
          <div class="cell" style="width:25%"><%=list.title%></div>
          <div class="cell" style="width:25%"><%=list.description%></div>
          <div class="cell" style="width:25%"><%= sanitize TodoListsHelper.GetItems(list)%></div>
          <div class="cell" style="width:8%"><%=link_to "Edit", edit_todo_list_path(list)%></div>
          <div class="cell" style="width:9%"><%=link_to "Manage", todo_list_todo_items_path(list)%></div>        
          <div class="cell" style="width:8%"><%=link_to "Delete", todo_list_path(list), method: :delete, data: {confirm: "are you sure?"}%></div>
      </div>

      <%end%>           

    </div>

  <h3><%= link_to 'Add New Todo List', new_todo_list_path, id: "addnew" %></h3>
  <%= button_to "Search To Dos Items", search_index_path, class: 'button', method: :get %>
</div>

</div>

app/views/todo_lists/new.html.erb
<div class="wrapper" style="padding-bottom: 0px;">
    <%if @todolist.new_record? %>
        <div class="fontblue"><h1>New Todo List</h1></div>
    <%else%>
        <div class="fontblue"><h1>Edit Todo Lists</h1></div>
    <%end%>
</div>

<%= render 'form', todolist: @todolist%>